import logging
from pathlib import Path

from medperf.commands.execution.execution_flow import ExecutionFlow
from medperf.commands.execution.plan import BenchmarkPlan
from medperf.entities.dataset import Dataset
from medperf.entities.benchmark import Benchmark
from medperf.entities.report import TestReport
from medperf.enums import BenchmarkTopology
from medperf.exceptions import InvalidArgumentError
from medperf.utils import sanitize_path
from .validate_params import CompatibilityTestParamsValidator
from .utils import download_demo_data, prepare_cube, create_test_dataset, prepare_model
import medperf.config as config


class CompatibilityTestExecution:
    @classmethod
    def run(
        cls,
        benchmark: int = None,
        data_prep: str = None,
        model: str = None,
        evaluator: str = None,
        data_uid: str = None,
        no_cache: bool = False,
        skip_data_preparation_step: bool = False,
        model_decryption_key: Path = None,
        benchmark_script: str = None,
    ) -> tuple[str, dict]:
        """Execute a test workflow. Components of a complete workflow should be passed.
        When only the benchmark is provided, it implies the following workflow will be used:
        - the benchmark's demo dataset is used as the raw data
        - the benchmark's data preparation cube is used
        - the benchmark's reference model cube is used
        - the benchmark's metrics cube is used

        Overriding benchmark's components:
        - The data prepration, model, and metrics cubes can be overriden by specifying a cube either
        as an integer (registered) or a path (local). The path can refer either to the mlcube config
        file or to the mlcube directory containing the mlcube config file.
        - Instead of using the demo dataset of the benchmark, The input raw data can be overriden by providing:
            - a demo dataset url and its hash
            - data path and labels path
        - A prepared dataset can be directly used. In this case the data preparator cube is never used.
        The prepared data can be provided by either specifying an integer (registered) or a hash of a
        locally prepared dataset.

        Whether the benchmark is provided or not, the command will fail either if the user fails to
        provide a valid complete workflow, or if the user provided extra redundant parameters.


        Args:
            benchmark (int, optional): Benchmark to run the test workflow for
            data_prep (str, optional): data preparation mlcube uid or local path.
            model (str, optional): model mlcube uid or local path.
            evaluator (str, optional): evaluator mlcube uid or local path.
            data_path (str, optional): path to a local raw data
            labels_path (str, optional): path to the labels of the local raw data
            demo_dataset_url (str, optional): Identifier to download the demonstration dataset tarball file.\n
            See `medperf mlcube submit --help` for more information
            demo_dataset_hash (str, optional): The hash of the demo dataset tarball file
            data_uid (str, optional): A prepared dataset UID
            no_cache (bool): Whether to ignore cached results of the test execution. Defaults to False.
            offline (bool): Whether to disable communication to the MedPerf server and rely only on
            local copies of the server assets. Defaults to False.
            benchmark_script (str, optional): benchmark script mlcube uid or local path.
            Required for asset models, which cannot run themselves.

        Returns:
            (str): Prepared Dataset UID used for the test. Could be the one provided or a generated one.
            (dict): Results generated by the test.
        """
        logging.info("Starting test execution")
        test_exec = cls(
            benchmark,
            data_prep,
            model,
            evaluator,
            data_uid,
            no_cache,
            skip_data_preparation_step,
            model_decryption_key=model_decryption_key,
            benchmark_script=benchmark_script,
        )
        test_exec.validate()
        test_exec.set_data_source()
        test_exec.process_benchmark()
        with config.ui.interactive():
            test_exec.prepare_cubes()
            test_exec.prepare_model()
            test_exec.resolve_topology()
            test_exec.prepare_dataset()
        test_exec.initialize_report()
        results = test_exec.cached_results()
        if results is None:
            results = test_exec.execute()
            test_exec.write(results)
        else:
            logging.info("Existing results are found. Test would not be re-executed.")
            logging.debug(f"Existing results: {results}")
        return test_exec.data_uid, results

    def __init__(
        self,
        benchmark: int = None,
        data_prep: str = None,
        model: str = None,
        evaluator: str = None,
        data_uid: str = None,
        no_cache: bool = False,
        skip_data_preparation_step: bool = False,
        model_decryption_key: Path = None,
        benchmark_script: str = None,
    ):
        self.benchmark_uid = benchmark
        self.data_prep = data_prep
        self.model = model
        self.evaluator = evaluator
        self.benchmark_script = benchmark_script
        self.data_uid = data_uid
        self.no_cache = no_cache
        self.skip_data_preparation_step = skip_data_preparation_step

        # This property will be set to either "path", "demo", "prepared", or "benchmark"
        self.data_source = None

        self.dataset = None
        self.data_prep_cube = None
        self.model_obj = None
        self.evaluator_cube = None
        self.benchmark_script_cube = None
        self.topology = None

        # Decryption key is used for compatibility test of encrypted containers
        self.model_decryption_key = sanitize_path(model_decryption_key)

        self.validator = CompatibilityTestParamsValidator(
            self.benchmark_uid,
            self.data_prep,
            self.model,
            self.evaluator,
            self.data_uid,
            self.benchmark_script,
        )

    def validate(self):
        self.validator.validate()

    def set_data_source(self):
        self.data_source = self.validator.get_data_source()

    def process_benchmark(self):
        """Process the benchmark input if given. Sets the needed parameters from
        the benchmark."""
        if not self.benchmark_uid:
            return

        benchmark = Benchmark.get(self.benchmark_uid)
        if self.data_source != "prepared":
            self.data_prep = self.data_prep or benchmark.data_preparation_mlcube
        self.model = self.model or benchmark.reference_model
        self.topology = benchmark.topology_enum
        self.evaluator = self.evaluator or benchmark.data_evaluator_mlcube
        self.benchmark_script = self.benchmark_script or benchmark.benchmark_script
        if self.data_source == "benchmark":
            self.demo_dataset_url = benchmark.demo_dataset_tarball_url
            self.demo_dataset_hash = benchmark.demo_dataset_tarball_hash
            self.skip_data_preparation_step = benchmark.metadata.get(
                "demo_dataset_already_prepared", False
            )

    def prepare_cubes(self):
        """Prepares the mlcubes. If the provided mlcube is a path, it will create
        a temporary uid and link the cube path to the medperf storage path."""

        if self.data_source != "prepared":
            logging.info(
                f"Establishing the data preparation container: {self.data_prep}"
            )
            self.data_prep_cube = prepare_cube(self.data_prep)

        if self.evaluator:
            logging.info(f"Establishing the evaluator container: {self.evaluator}")
            self.evaluator_cube = prepare_cube(self.evaluator)

        if self.benchmark_script:
            logging.info(
                f"Establishing the benchmark script container: {self.benchmark_script}"
            )
            self.benchmark_script_cube = prepare_cube(self.benchmark_script)

    def prepare_model(self):
        logging.info(f"Establishing the model container: {self.model}")
        self.model_obj = prepare_model(
            self.model, decryption_key_file_path=self.model_decryption_key
        )

    def resolve_topology(self):
        """Determines the topology of the workflow under test.

        A benchmark states its own topology. Without one, the topology follows
        from the kind of model and the containers the caller supplied."""
        if self.topology is not None:
            return

        if self.model_obj.is_container():
            self.topology = BenchmarkTopology.BYO_INFERENCE_SCRIPT
        elif not self.benchmark_script_cube:
            raise InvalidArgumentError(
                "An asset model cannot run itself. Provide a benchmark script"
                " that loads it, or test against a benchmark."
            )
        elif self.evaluator_cube:
            self.topology = BenchmarkTopology.INFERENCE_SCRIPT
        else:
            self.topology = BenchmarkTopology.END_TO_END_SCRIPT

        if self.topology.requires_evaluator and not self.evaluator_cube:
            raise InvalidArgumentError(
                f"A {self.topology.value} workflow requires a metrics container"
            )
        if not self.topology.requires_benchmark_script and self.benchmark_script_cube:
            raise InvalidArgumentError(
                f"A {self.topology.value} workflow does not use a benchmark script"
            )

    def prepare_dataset(self):
        """Assigns the data_uid used for testing and retrieves the dataset.
        If the data is not prepared, it calls the data preparation step
        on the given local data path or using a remote demo dataset."""

        logging.info("Establishing data_uid for test execution")
        if self.data_source != "prepared":
            data_path, labels_path, metadata_path = download_demo_data(
                self.demo_dataset_url, self.demo_dataset_hash
            )

            self.data_uid = create_test_dataset(
                data_path,
                labels_path,
                metadata_path,
                self.data_prep_cube,
                self.skip_data_preparation_step,
            )

        self.dataset = Dataset.get(self.data_uid)

    def initialize_report(self):
        """Initializes an instance of `TestReport` to hold the current test information."""

        report_data = {
            "demo_dataset_url": self.demo_dataset_url,
            "demo_dataset_hash": self.demo_dataset_hash,
            "prepared_data_hash": self.data_uid,
            "data_preparation_mlcube": self.data_prep_cube.identifier,
            "model": self.model_obj.identifier,
            "topology": self.topology.value,
            "data_evaluator_mlcube": (
                self.evaluator_cube.identifier if self.evaluator_cube else None
            ),
            "benchmark_script": (
                self.benchmark_script_cube.identifier
                if self.benchmark_script_cube
                else None
            ),
        }
        self.report = TestReport(**report_data)

    def cached_results(self):
        """checks the existance of, and retrieves if possible, the compatibility test
        result. This method is called prior to the test execution.

        Returns:
            (dict|None): None if the results does not exist or if self.no_cache is True,
            otherwise it returns the found results.
        """
        if self.no_cache:
            return
        uid = self.report.local_id
        try:
            report = TestReport.get(uid)
        except InvalidArgumentError:
            return
        logging.info(f"Existing report {uid} was detected.")
        logging.info("The compatibilty test will not be re-executed.")
        return report.results

    def execute(self):
        """Runs the test execution flow and returns the results

        Returns:
            dict: returns the results of the test execution.
        """
        plan = BenchmarkPlan(
            topology=self.topology,
            benchmark_id=self.benchmark_uid,
            script=self.benchmark_script_cube,
            evaluator=self.evaluator_cube,
        )
        execution_summary = ExecutionFlow.run(
            plan=plan,
            dataset=self.dataset,
            model=self.model_obj,
            ignore_model_errors=False,
        )
        return execution_summary["results"]

    def write(self, results):
        """Writes a report of the test execution to the disk
        Args:
            results (dict): the results of the test execution
        """
        self.report.set_results(results)
        self.report.write()
