name: docs-ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.2.4 mkdocs-autorefs==0.4.1 mkdocs-gen-files==0.3.4 mkdocs-git-revision-date-plugin==0.3.2 mkdocs-literate-nav==0.4.1 mkdocs-material==8.2.5 mkdocs-material-extensions==1.0.3 mkdocstrings==0.18.1 mkdocstrings-python-legacy==0.2.2
      - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: mkdocs gh-deploy --force