name: TMP Test Chrome

on: pull_request

jobs:
  setup:
    name: local-deploy
    runs-on: ubuntu-latest
    env:
      MOCK_USERS_PASSWORD: "Benchmark123"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Setup Chrome
      run: |
        sudo apt-get install -y wget
        wget -O chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.198-1_amd64.deb
        sudo apt install -y chrome.deb
        rm chrome.deb

    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install -e cli/
        pip install -r cli/test-requirements.txt

    - name: Run login test
      working-directory: .
      run: sh cli/test_login.sh