name: test selenium-chrome workflow

on: pull_request

jobs:
  setup:
    name: local-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f cli/requirements.txt ]; then pip install -e cli; fi
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi
        pip install selenium==4.10.0 webdriver-manager==3.8.6

    - name: Set server environment vars
      working-directory: ./server
      run: cp .env.example .env

    - name: Run django server in background with generated certs
      working-directory: ./server
      run: sh setup-dev-server.sh & sleep 6

    # - name: Install chrome dependencies
    #   working-directory: /tmp
    #   run: apt update && apt install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    - name: Run client integration tests
      working-directory: .
      run: sh cli/cli_tests.sh
